<a href="https://colab.research.google.com/github/TheCodeTester860/AntonioCabrera/blob/main/MineriaDeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mineria de datos

## Primer Parcial

### Introduccion

#### Conceptos
##### En programación, la minería de datos se conceptualiza como la aplicación técnica de algoritmos para encontrar patrones. No es tanto una "ciencia" holística, sino un proceso computacional específico.

#####Definición Técnica: Es el subconjunto de la informática centrado en el descubrimiento automático de patrones (correlaciones, anomalías, clústeres) en grandes conjuntos de datos utilizando métodos de la inteligencia artificial, aprendizaje automático, estadística y sistemas de bases de datos.

#####Concepto en Programación:

#####El "Motor": Para un programador, la minería de datos es la implementación de la lógica algorítmica. Es escribir el código que ejecuta un algoritmo de Clustering (agrupamiento) o de Regresión sobre una matriz de datos limpia.

#####Enfoque: Se centra en el algoritmo y su eficiencia. ¿Cómo procesamos 1 millón de filas para encontrar fraudes?

#####Bibliotecas comunes: En Python, esto se traduce en usar librerías como Scikit-learn (para algoritmos) o Weka (en Java).

#####Analogía: Si los datos son una montaña de tierra, la minería de datos es el pico y la pala (la herramienta y la técnica) que usas para extraer las pepitas de oro.

####  Ciencia de datos

#####La ciencia de datos es un concepto más arquitectónico y multidisciplinario. En programación, se ve como el ciclo de vida completo del manejo de datos, donde la programación es el pegamento que une estadística, negocio y tecnología.

#####Definición General: Es un campo interdisciplinario que utiliza métodos científicos, procesos, algoritmos y sistemas para extraer conocimiento e insights de datos estructurados y no estructurados. Abarca desde la limpieza de datos hasta la visualización y la toma de decisiones.

#####Concepto en Programación:

#####El "Pipeline" (Tubería): Para un programador, hacer Data Science implica construir un flujo de trabajo (pipeline). Implica escribir scripts para extraer datos (SQL/Scraping), limpiarlos (Pandas), analizarlos (donde entra la minería de datos) y visualizarlos (Matplotlib/Tableau).

#####Enfoque: Se centra en la solución del problema de negocio. El código es un medio para responder una pregunta compleja.

#####Herramientas: Lenguajes como Python y R, entornos como Jupyter Notebooks, y plataformas de nube (AWS, Azure).

#####Analogía: La ciencia de datos es toda la operación geológica: desde decidir dónde excavar, gestionar la logística de la mina, usar el pico y la pala (minería de datos), hasta refinar el oro y venderlo en el mercado.

#### Tarea 1

In [ ]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [ ]:
len?

In [ ]:
L = [1, 2, 3]

In [ ]:
L?

In [ ]:
def square(a):
    """Return the square of a."""
    return a ** 2

In [ ]:
square?

### IPython Magic Commands

In [ ]:
#El comando magico %timeit sirve para evaluar el desempeño, en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

88 µs ± 22.7 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
#El comando magico %%timeit sirve tambien para evaluar el desempeño, solo que este abarca varias lineas de codigo en su lugar
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

94.4 µs ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

### IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': '36d34a5800f0',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [ ]:
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

###The Basics of NumPy Arrays

#### NumPy Array Attributes


In [4]:
import numpy as np

In [5]:
np.random.seed(0)  # seed for reproducibility


In [6]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [7]:
print("x3 ndim: ", x3.ndim) #LA PROPIEDAD NDIM NOS DICE EL MUMERO DE DIMENSIONES
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [8]:
print("dtype:", x3.dtype) #dtype nos dice el tipo de datos

dtype: int64


In [9]:
print("itemsize:", x3.itemsize, "bytes") #
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


#### Array Indexing: Accessing Single Elements

In [10]:
x1

array([5, 0, 3, 3, 7, 9])

In [11]:
x1[0] # Colocamos el indice del elemento a extraer, en este caso el primer elemento tienen el indice 0

np.int64(5)

In [12]:
x1[4]

np.int64(7)

In [13]:
x1[-1] # Nos regresa el ultimo elemento del notarray

np.int64(9)

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [15]:
x2[0, 0]

np.int64(3)

In [16]:
x2[0, 2]

np.int64(2)

In [17]:
x2[0, 0] = 12 #Asignar un nuevo valor (12) al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Media (Mean)

In [18]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


### Promedio (Average) y Promedio Ponderado


In [19]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [20]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


### Mediana


In [21]:
mediana = np.median(data)

### Varianza y Desviación Estándar


In [22]:
varianza = np.var(data)
desviacion = np.std(data)

### Generación de Datos Aleatorios

In [23]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


### Correlación

In [25]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])